if (USE_TOOTLE AND (WIN32 OR WIN64))
	target_compile_definitions( ${THIS_PROJECT} PRIVATE USE_TOOTLE )
	target_include_directories( ${THIS_PROJECT} PRIVATE "${SDK_DIR}/AMD/Tootle-2.2.150/include" )
	if (WIN64)
		target_link_libraries( ${THIS_PROJECT} PRIVATE "${SDK_DIR}/AMD/Tootle-2.2.150/lib/TootleDLL_2k8_64.lib" )
	elseif(WIN32)
		target_link_libraries( ${THIS_PROJECT} PRIVATE "${SDK_DIR}/AMD/Tootle-2.2.150/lib/TootleDLL_2k8.lib" )
	endif()
endif()
